version: '3.7'

x-logging:
    &default-json-logging
    driver: json-file
    options:
        max-size: "10m"
        max-file: "1"

services:
    elasticsearch:
        image: comworkio/elasticsearch:7.9.1-1.8-arm
        container_name: elasticsearch
        restart: always
        expose:
            - "9200"
            - "9300"
        environment:
            discovery.type: "single-node"
            ES_JAVA_OPTS: "-Xms64m -Xmx64m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        logging: *default-json-logging

    kibana:
        image: comworkio/kibana:7.9.1-1.9-arm
        container_name: kibana
        restart: always
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        links:
            - elasticsearch:elasticsearch
        logging: *default-json-logging

    fluentd:
        build:
         context: ./fluentd
         dockerfile: Dockerfile
        container_name: fluentd
        image: wsrak/rpi-fluentd:latest
        ports:
            - "24224:24224"
        volumes:
            - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
        depends_on:
            - elasticsearch
        logging: *default-json-logging

volumes:
    elasticsearch-data:
        driver: local
